apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
  labels:
    app.kubernetes.io/name: clickhouse
---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    app.kubernetes.io/name: airflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-sources
  labels:
    app.kubernetes.io/name: data-sources
