apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: data-sources
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    dynamic_shared_memory_type = posix
    wal_level = logical
    max_wal_senders = 4
    max_replication_slots = 4
